# Site settings
title: Random Thoughts of Jimmy
email: jimmy@sambuo.com
description: > # this means to ignore newlines until "baseurl:"
  This is Jimmy Sambuo's super awesome website. I'll write
  about my random thought here, as well as some of the projects
  that I work on.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.sambuo.com" # the base hostname & protocol for your site
twitter_username: jsambuo
github_username:  jsambuo

# Build settings
markdown: kramdown
